### ISSUE TITLE
Create Helper for Books

### ISSUE THREAD

**Issue by FitzAfful** [LibTrackTeam/LibTrack-iOS#4]
Currently, this Helper will have only 2 methods. Converting a BookItem to a GoogleBookItem and vice versa. 
Check CryptHelper and FirebaseService on how to create a Helper and use it.

To work on this, pull from the Development breach, create a new branch and work on it.
After completing this, create a pull request and attach this issue. I will review it and close it.

**Comment by KobbySkywalker** [comment]
noted.
